### ISSUE TITLE
story: Support sarif-to-comment optional failon error code

### ISSUE THREAD

**Issue by tomwillis608** [sett-and-hive/sarif-to-comment-action#174]
### Describe the User Story

As an engineer using this action,
So that the action can return a failure code if there is a finding in the SARIF file,
I want the action to optionally return the failure code of the `sarif-to-comment` application.

### Acceptance Criteria

- [ ]  The action supports an option to return the error code the failon output of of the `sarif-to-comment` application.

### Definition of Done

- [ ] Acceptance criteria met
- [ ] Usability tests passed - this user story should be easy to use by real users
- [ ] Code refactored for clarity - code must be clean, self-documenting code
- [ ] Dependency Rule followed - higher-level code should not depend directly on lower-level code
- [ ] Source code merged
- [ ] Unit test coverage of our code > 90%
- [ ] Security reviewed and reported - includes vulnerability and compliance scanning
- [ ] Code quality checks passed
- [ ] Build process updated if needed
- [ ] API documentation updated if needed

## Tasks

- [ ] Add tests
- [ ] Add option
- [ ] Document option

### Related Feature Request

#143
